FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY public /app/static

WORKDIR /app

CMD ["python3", "-m", "http.server", "3000", "--directory", "/app/static"]
